2019-12-29 13:09:27,318 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 288510ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-29 15:13:07,454 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 6860920ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-29 20:05:04,285 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 3674685ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-29 21:00:23,009 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 3298722ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-30 08:15:01,969 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 33218083ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-30 10:37:59,757 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 8577725ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-30 10:39:10,293 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 70526ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2019-12-30 11:02:53,940 ERROR 47200 nodejs.ClusterClientNoResponseError: client no response in 1386064ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 47200
hostname: kubandeMacBook-Pro.local

2020-01-12 10:55:03,511 ERROR 27191 [egg-mongoose] mongodb://127.0.0.1:27017/interview disconnected
2020-01-12 10:55:03,512 ERROR 27191 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:189:13)
    at createConnection (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:985:11)
    at makeConnection (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 27191
hostname: kubandeMacBook-Pro.local

2020-01-12 10:55:03,514 ERROR 27191 nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:189:13)
    at createConnection (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:985:11)
    at makeConnection (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 27191
hostname: kubandeMacBook-Pro.local

2020-01-12 10:55:03,515 ERROR 27191 [-/127.0.0.1/-/1ms GET /] nodejs.MongoNetworkError: [egg-mongoose]failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:189:13)
    at createConnection (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:562:14)
    at connect (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/pool.js:985:11)
    at makeConnection (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:40:11)
    at callback (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.err (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
name: "MongoNetworkError"
errorLabels: ["TransientTransactionError"]
pid: 27191
hostname: kubandeMacBook-Pro.local

2020-01-12 13:36:33,424 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 3096001ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-12 21:10:29,004 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 10194914ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-13 02:29:49,773 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 7218471ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-13 09:25:04,898 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 24915095ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-13 10:21:38,496 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 3273564ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-13 10:23:37,427 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 80119ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-13 10:25:55,885 ERROR 27335 nodejs.ClusterClientNoResponseError: client no response in 138457ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 27335
hostname: kubandeMacBook-Pro.local

2020-01-14 07:15:08,329 ERROR 30186 nodejs.ClusterClientNoResponseError: client no response in 41271240ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30186
hostname: kubandeMacBook-Pro.local

2020-01-14 07:48:24,856 ERROR 30186 nodejs.ClusterClientNoResponseError: client no response in 1996453ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30186
hostname: kubandeMacBook-Pro.local

2020-01-14 08:02:52,576 ERROR 30186 nodejs.ClusterClientNoResponseError: client no response in 867706ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30186
hostname: kubandeMacBook-Pro.local

2020-01-14 10:22:50,282 ERROR 30186 nodejs.ClusterClientNoResponseError: client no response in 6399669ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30186
hostname: kubandeMacBook-Pro.local

2020-01-14 10:24:52,039 ERROR 30186 nodejs.ClusterClientNoResponseError: client no response in 82036ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/kuban/Desktop/InterviewQuestionManage/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 30186
hostname: kubandeMacBook-Pro.local

